services:
  frontend:
    image: "grocy/frontend:v4.0.3"
    depends_on:
      - backend
    expose:
      - "8080"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped

  backend:
    image: "grocy/backend:v4.0.3"
    expose:
      - "9000"
    read_only: true
    tmpfs:
      - /tmp
      - /var/www/data/viewcache:mode=755,uid=82,gid=82,size=16m
    volumes:
      - app-db:/var/www/data
    restart: unless-stopped

volumes:
  app-db:
